

DEB_DL_URL := https://archive.raspberrypi.org/debian/pool/main/b/bluez/

DEB_NAME_TAR := libbluetooth3_5.43-2+rpt2+deb9u2_armhf.deb

DEB_SHA1SUM:=2e7a0adb224a6aeda4871bcaa23d9eda8e3d3232

# Build package using debian recipe
include ../../system-build/makefile/Makefile.deb
