

AUTOTOOLS_DL_URL := https://gstreamer.freedesktop.org/src/gst-plugins-base/

AUTOTOOLS_NAME_TAR := gst-plugins-base-1.10.5.tar.xz

AUTOTOOLS_SHA1SUM:=ad123d3f7091bd758f85c38831f464f171be2dce

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=$(BOARD_LIBRARY_BOARD_INSTALLDIR) --host=$(BOARD_LIBRARY_HOST)

# Build package using autotools recipe
include ../../system-build/makefile/Makefile.autotools
