

AUTOTOOLS_DL_URL := http://downloads.sourceforge.net/expat/

AUTOTOOLS_NAME_TAR := expat-2.1.0.tar.gz

AUTOTOOLS_SHA1SUM:=b08197d146930a5543a7b99e871cba3da614f6f0

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=$(MACHINE_LIBRARY_MACHINE_INSTALLDIR) --host=$(MACHINE_LIBRARY_HOST) --disable-static

# Build package using autotools recipe
include ../../system-build/makefile/Makefile.autotools
