

AUTOTOOLS_DL_URL := ftp://xmlsoft.org/libxml2/

AUTOTOOLS_NAME_TAR := libxml2-2.9.4.tar.gz

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=/usr/lib/arm-linux-gnueabihf/ --host=arm \
--with-python=no

# Build package using autotools recipe
include ../../system-build/Makefile.autotools



