

AUTOTOOLS_DL_URL := ftp://sourceware.org/pub/libffi/

AUTOTOOLS_NAME_TAR := libffi-3.2.1.tar.gz

AUTOTOOLS_SHA1SUM:=280c265b789e041c02e5c97815793dfc283fb1e6

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=$(MACHINE_LIBRARY_MACHINE_INSTALLDIR) --host=$(MACHINE_LIBRARY_HOST)

# Build package using autotools recipe
include ../../system-build/makefile/Makefile.autotools
