

AUTOTOOLS_DL_URL := ftp://sourceware.org/pub/libffi/

AUTOTOOLS_NAME_TAR := libffi-3.2.1.tar.gz

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=/usr/lib/arm-linux-gnueabihf/ --host=arm

# Build package using autotools recipe
include ../../system-build/Makefile.autotools
