include ../Make.defs

all: header

header:
	@$(ECHO) "${MSG_INFO}Application build${MSG_END}"

install:
	@$(ECHO) "${MSG_INFO}  Install applications${MSG_END}"

uninstall:
	@$(ECHO) "${MSG_INFO}  Uninstall applications${MSG_END}"
	$(V) $(RM) applications-install
