

AUTOTOOLS_DL_URL := https://gstreamer.freedesktop.org/src/gst-omx/

AUTOTOOLS_NAME_TAR := gst-omx-1.10.5.tar.xz

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=$(BOARD_LIBRARY_BOARD_INSTALLDIR) --host=$(BOARD_ARCH)

# Build package using autotools recipe
include ../../system-build/makefile/Makefile.autotools
