

AUTOTOOLS_DL_URL := ftp://ftp.gnu.org/gnu/ncurses/

AUTOTOOLS_NAME_TAR := ncurses-6.0.tar.gz

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=/usr/lib/arm-linux-gnueabihf/ --host=arm

# Build package using autotools recipe
include ../../system-build/makefile/Makefile.autotools
