

DEB_DL_URL := https://archive.raspberrypi.org/debian/pool/main/b/bluez/

DEB_NAME_TAR := libbluetooth-dev_5.43-2+rpt2+deb9u2_armhf.deb

DEB_SHA1SUM:=ce051a39f12bb49fc02d5535f656013427560cc7

# Build package using debian recipe
include ../../system-build/makefile/Makefile.deb
