

AUTOTOOLS_DL_URL := http://ijg.org/files/

AUTOTOOLS_NAME_TAR := jpegsrc.v9c.tar.gz

AUTOTOOLS_SHA1SUM:=2ce111c8c0ac828a44b13ad28c265e954a342d07

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=$(MACHINE_LIBRARY_MACHINE_INSTALLDIR) --host=$(MACHINE_LIBRARY_HOST)

# Build package using autotools recipe
include ../../system-build/makefile/Makefile.autotools
