

AUTOTOOLS_DL_URL := https://gstreamer.freedesktop.org/src/gst-plugins-good/

AUTOTOOLS_NAME_TAR := gst-plugins-good-1.10.5.tar.xz

AUTOTOOLS_SHA1SUM:=e982761df8dfb925828277fa55f08935ff945b47

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=$(MACHINE_LIBRARY_MACHINE_INSTALLDIR) --host=$(MACHINE_LIBRARY_HOST)

# Build package using autotools recipe
include ../../system-build/makefile/Makefile.autotools
