

AUTOTOOLS_DL_URL := https://gstreamer.freedesktop.org/src/gst-plugins-ugly/

AUTOTOOLS_NAME_TAR := gst-plugins-ugly-1.10.5.tar.xz

AUTOTOOLS_SHA1SUM:=c1728b092573e233ec2e723d960993f553475627

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=$(MACHINE_LIBRARY_MACHINE_INSTALLDIR) --host=$(MACHINE_LIBRARY_HOST)

# Build package using autotools recipe
include ../../system-build/makefile/Makefile.autotools
