

AUTOTOOLS_DL_URL := https://ftp.pcre.org/pub/pcre/

AUTOTOOLS_NAME_TAR := pcre-8.40.tar.gz

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=/usr/lib/arm-linux-gnueabihf/ --host=arm-linux-gnu

# Build package using autotools recipe
include ../../system-build/Makefile.autotools
