

AUTOTOOLS_DL_URL := https://ftp.pcre.org/pub/pcre/

AUTOTOOLS_NAME_TAR := pcre-8.40.tar.gz

AUTOTOOLS_SHA1SUM:=10384eb3d411794cc15f55b9d837d3f69e35391e

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=$(BOARD_LIBRARY_BOARD_INSTALLDIR) --host=$(BOARD_LIBRARY_HOST)

# Build package using autotools recipe
include ../../system-build/makefile/Makefile.autotools
