

AUTOTOOLS_DL_URL := http://ftp.gnome.org/pub/GNOME/sources/glib/2.50/

AUTOTOOLS_NAME_TAR := glib-2.50.3.tar.xz

AUTOTOOLS_SHA1SUM:=3177471fb11fd2fd5abb77ec0675ee0049521009

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=$(MACHINE_LIBRARY_MACHINE_INSTALLDIR) --host=$(MACHINE_LIBRARY_HOST)

# Build package using autotools recipe
include ../../system-build/makefile/Makefile.autotools
