

AUTOTOOLS_DL_URL := http://ftp.gnome.org/pub/GNOME/sources/glib/2.50/

AUTOTOOLS_NAME_TAR := glib-2.50.3.tar.xz

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=/usr/lib/arm-linux-gnueabihf/ --host=arm

# Build package using autotools recipe
include ../../system-build/Makefile.autotools



