

DEB_DL_URL := http://ftp.debian.org/debian/pool/main/i/i2c-tools/

DEB_NAME_TAR := i2c-tools_3.1.2-3_armhf.deb

DEB_SHA1SUM:=4e5efe542ea9d900774d5cb21c6a636910609b82

# Build package using debian recipe
include ../../system-build/makefile/Makefile.deb
