

AUTOTOOLS_DL_URL := https://sqlite.org/2017/

AUTOTOOLS_NAME_TAR := sqlite-autoconf-3170000.tar.gz

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=/usr/lib/arm-linux-gnueabihf/ --host=arm

# Build package using autotools recipe
include ../../system-build/makefile/Makefile.autotools
