

AUTOTOOLS_DL_URL := https://sqlite.org/2017/

AUTOTOOLS_NAME_TAR := sqlite-autoconf-3170000.tar.gz

AUTOTOOLS_SHA1SUM:=7bcff1c158ed9e2c0e159c1b4b6c36d4d65dff8c

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=$(BOARD_LIBRARY_BOARD_INSTALLDIR) --host=$(BOARD_LIBRARY_HOST)

# Build package using autotools recipe
include ../../system-build/makefile/Makefile.autotools
