

AUTOTOOLS_DL_URL := https://gstreamer.freedesktop.org/src/gst-rtsp-server/

AUTOTOOLS_NAME_TAR := gst-rtsp-server-1.10.5.tar.xz

AUTOTOOLS_SHA1SUM:=9b5be3d5459eefa004c6db6cdf2a8b24a93006bb

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=$(BOARD_LIBRARY_BOARD_INSTALLDIR) --host=$(BOARD_LIBRARY_HOST)

# Build package using autotools recipe
include ../../system-build/makefile/Makefile.autotools
