

AUTOTOOLS_DL_URL := https://dbus.freedesktop.org/releases/dbus/

AUTOTOOLS_NAME_TAR := dbus-1.12.10.tar.gz

AUTOTOOLS_SHA1SUM:=efd426031424519011e46d28256626a5ca20195c

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=$(MACHINE_LIBRARY_MACHINE_INSTALLDIR) --host=$(MACHINE_LIBRARY_HOST)

# Build package using autotools recipe
include ../../system-build/makefile/Makefile.autotools
