

AUTOTOOLS_DL_URL := http://download.savannah.gnu.org/releases/attr/

AUTOTOOLS_NAME_TAR := attr-2.4.47.src.tar.gz

AUTOTOOLS_SHA1SUM:=5060f0062baee6439f41a433325b8b3671f8d2d8

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=$(BOARD_LIBRARY_BOARD_INSTALLDIR) --host=$(BOARD_LIBRARY_HOST)

# Build package using autotools recipe
include ../../system-build/makefile/Makefile.autotools
