

# Build package using autotools recipe
include ../../system-build/Makefile.autotools

AUTOTOOLS_DL_URL := http://www.zlib.net/

AUTOTOOLS_NAME_TAR := zlib-1.2.11.tar.gz

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=/usr/lib/arm-linux-gnueabihf/
