

AUTOTOOLS_DL_URL := http://www.zlib.net/

AUTOTOOLS_NAME_TAR := zlib-1.2.11.tar.gz

AUTOTOOLS_SHA1SUM:=e6d119755acdf9104d7ba236b1242696940ed6dd

AUTOTOOLS_FLAGS += --prefix=/usr --libdir=$(MACHINE_LIBRARY_MACHINE_INSTALLDIR)

# Build package using autotools recipe
include ../../system-build/makefile/Makefile.autotools
